import io
import logging
from datetime import date
from decimal import Decimal
from typing import Any

logger = logging.getLogger(__name__)

def format_currency(amount: float | Decimal) -> str:
    if isinstance(amount, Decimal):
        amount = float(amount)
    return f"₹{amount:,.2f}"

def format_date(d: date | str | None) -> str:
    if d is None:
        return ""
    if isinstance(d, str):
        return d
    return d.strftime("%d-%b-%Y")

def generate_invoice_html(invoice: dict, company: dict, party: dict | None = None) -> str:
    lines = invoice.get('lines', [])
    return f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Invoice {invoice.get('invoice_number', '')}</title>
    <style>
        body {{ font-family: Arial, sans-serif; font-size: 12px; margin: 20px; }}
        .header {{ display: flex; justify-content: space-between; margin-bottom: 20px; }}
        .company-info {{ width: 50%; }}
        .invoice-info {{ width: 40%; text-align: right; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #f5f5f5; }}
        .totals {{ margin-top: 20px; text-align: right; }}
        .totals table {{ width: 300px; margin-left: auto; }}
        .footer {{ margin-top: 40px; font-size: 10px; color: #666; }}
        .GSTIN {{ font-size: 10px; }}
    </style>
</head>
<body>
    <div class="header">
        <div class="company-info">
            <h2>{company.get('company_name', 'Company')}</h2>
            <p class="GSTIN">GSTIN: {company.get('gstin', '')}</p>
            <p>PAN: {company.get('pan', '')}</p>
            <p>State: {company.get('state_code', '')}</p>
        </div>
        <div class="invoice-info">
            <h1>INVOICE</h1>
            <p><strong>Invoice No:</strong> {invoice.get('invoice_number', '')}</p>
            <p><strong>Date:</strong> {format_date(invoice.get('invoice_date'))}</p>
            <p><strong>Type:</strong> {invoice.get('invoice_type', 'Regular')}</p>
            <p><strong>Status:</strong> {invoice.get('status', '')}</p>
        </div>
    </div>

    {f'''
    <div class="party-info">
        <h3>Bill To:</h3>
        <p><strong>{party.get('party_name', '')}</strong></p>
        <p>GSTIN: {party.get('gstin', 'N/A')}</p>
        <p>State: {party.get('state_code', '')}</p>
    </div>
    ''' if party else ''}

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Item</th>
                <th>HSN</th>
                <th>Qty</th>
                <th>Rate</th>
                <th>Discount</th>
                <th>Taxable</th>
                <th>GST %</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            {''.join(f'''
            <tr>
                <td>{i+1}</td>
                <td>{line.get('item_name', '')}</td>
                <td>{line.get('hsn_code', '')}</td>
                <td>{line.get('quantity', 0)} {line.get('unit', '')}</td>
                <td>{format_currency(line.get('unit_price', 0))}</td>
                <td>{format_currency(line.get('discount_amount', 0))}</td>
                <td>{format_currency(line.get('taxable_value', 0))}</td>
                <td>{line.get('gst_rate', 0)}%</td>
                <td>{format_currency(line.get('total_amount', 0))}</td>
            </tr>
            ''' for i, line in enumerate(lines))}
        </tbody>
    </table>

    <div class="totals">
        <table>
            <tr><td>Subtotal</td><td>{format_currency(invoice.get('subtotal', 0))}</td></tr>
            <tr><td>Discount</td><td>{format_currency(invoice.get('total_discount', 0))}</td></tr>
            <tr><td>CGST</td><td>{format_currency(invoice.get('total_cgst', 0))}</td></tr>
            <tr><td>SGST</td><td>{format_currency(invoice.get('total_sgst', 0))}</td></tr>
            <tr><td>IGST</td><td>{format_currency(invoice.get('total_igst', 0))}</td></tr>
            <tr><td>Round Off</td><td>{format_currency(invoice.get('round_off', 0))}</td></tr>
            <tr><td><strong>Grand Total</strong></td><td><strong>{format_currency(invoice.get('grand_total', 0))}</strong></td></tr>
        </table>
    </div>

    {f'''
    <div class="notes">
        <h4>Notes:</h4>
        <p>{invoice.get('notes', '')}</p>
    </div>
    ''' if invoice.get('notes') else ''}

    <div class="footer">
        <p>Generated by GST API Engine</p>
        <p>This is a computer-generated document. No signature required.</p>
    </div>
</body>
</html>
"""

def generate_invoice_pdf(invoice: dict, company: dict, party: dict | None = None) -> bytes:
    try:
        from weasyprint import HTML
        html_content = generate_invoice_html(invoice, company, party)
        pdf_bytes = HTML(string=html_content).write_pdf()
        return pdf_bytes
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        raise

def save_invoice_pdf(db, invoice_id: str, pdf_bytes: bytes, bucket: str = "invoices") -> str:
    import uuid
    from app.core.config import get_settings
    from app.services.storage_service import upload_file
    settings = get_settings()
    s3_key = f"invoices/{invoice_id}/{uuid.uuid4()}.pdf"
    url = upload_file(pdf_bytes, s3_key, "application/pdf", bucket or settings.s3_bucket)
    return url