// This file is auto-generated by json_serializable. Do not edit manually.

part of 'gl_entry.dart';

Map<String, dynamic> _$GLEntryToJson(GLEntry instance) => <String, dynamic>{
      'id': instance.id,
      'posting_date': instance.postingDate.toIso8601String(),
      'account': instance.account,
      'party_id': instance.partyId,
      'voucher_type': instance.voucherType,
      'voucher_id': instance.voucherId,
      'debit': instance.debit,
      'credit': instance.credit,
      'remarks': instance.remarks,
    };

GLEntry _$GLEntryFromJson(Map<String, dynamic> json) => GLEntry(
      id: json['id'] as String,
      postingDate: DateTime.parse(json['posting_date'] as String),
      account: json['account'] as String,
      partyId: json['party_id'] as String?,
      voucherType: json['voucher_type'] as String,
      voucherId: json['voucher_id'] as String,
      debit: (json['debit'] as num).toDouble(),
      credit: (json['credit'] as num).toDouble(),
      remarks: json['remarks'] as String? ?? '',
    );