// This file is auto-generated by json_serializable. Do not edit manually.
// Run: flutter pub run build_runner build --delete-conflicting-outputs

part of 'invoice.dart';

// Invoice
Map<String, dynamic> _$InvoiceToJson(Invoice instance) => <String, dynamic>{
      'invoice_id': instance.invoiceId,
      'invoice_number': instance.invoiceNumber,
      'invoice_kind': instance.invoiceKind,
      'invoice_type': instance.invoiceType,
      'status': instance.status,
      'invoice_date': instance.invoiceDate.toIso8601String(),
      'due_date': instance.dueDate?.toIso8601String(),
      'party_id': instance.partyId,
      'party_gstin': instance.partyGstin,
      'place_of_supply': instance.placeOfSupply,
      'supply_type': instance.supplyType,
      'payment_status': instance.paymentStatus,
      'subtotal': instance.subtotal,
      'total_discount': instance.totalDiscount,
      'total_cgst': instance.totalCgst,
      'total_sgst': instance.totalSgst,
      'total_igst': instance.totalIgst,
      'total_cess': instance.totalCess,
      'round_off': instance.roundOff,
      'grand_total': instance.grandTotal,
      'amount_paid': instance.amountPaid,
      'outstanding_amount': instance.outstandingAmount,
      'lines': instance.lines,
    };

Invoice _$InvoiceFromJson(Map<String, dynamic> json) => Invoice(
      invoiceId: json['invoice_id'] as String,
      invoiceNumber: json['invoice_number'] as String,
      invoiceKind: json['invoice_kind'] as String,
      invoiceType: json['invoice_type'] as String,
      status: json['status'] as String,
      invoiceDate: DateTime.parse(json['invoice_date'] as String),
      dueDate: json['due_date'] != null
          ? DateTime.parse(json['due_date'] as String)
          : null,
      partyId: json['party_id'] as String,
      partyGstin: json['party_gstin'] as String?,
      placeOfSupply: json['place_of_supply'] as String,
      supplyType: json['supply_type'] as String,
      paymentStatus: json['payment_status'] as String,
      subtotal: (json['subtotal'] as num).toDouble(),
      totalDiscount: (json['total_discount'] as num).toDouble(),
      totalCgst: (json['total_cgst'] as num).toDouble(),
      totalSgst: (json['total_sgst'] as num).toDouble(),
      totalIgst: (json['total_igst'] as num).toDouble(),
      totalCess: (json['total_cess'] as num).toDouble(),
      roundOff: (json['round_off'] as num).toDouble(),
      grandTotal: (json['grand_total'] as num).toDouble(),
      amountPaid: (json['amount_paid'] as num).toDouble(),
      outstandingAmount: (json['outstanding_amount'] as num).toDouble(),
      lines: (json['lines'] as List<dynamic>)
          .map((e) => InvoiceLine.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

// InvoiceLine
Map<String, dynamic> _$InvoiceLineToJson(InvoiceLine instance) =>
    <String, dynamic>{
      'line_no': instance.lineNo,
      'item_id': instance.itemId,
      'item_code': instance.itemCode,
      'item_name': instance.itemName,
      'hsn_code': instance.hsnCode,
      'sac_code': instance.sacCode,
      'quantity': instance.quantity,
      'unit': instance.unit,
      'unit_price': instance.unitPrice,
      'discount_amount': instance.discountAmount,
      'taxable_value': instance.taxableValue,
      'gst_rate': instance.gstRate,
      'cgst_amount': instance.cgstAmount,
      'sgst_amount': instance.sgstAmount,
      'igst_amount': instance.igstAmount,
      'cess_amount': instance.cessAmount,
      'total_amount': instance.totalAmount,
    };

InvoiceLine _$InvoiceLineFromJson(Map<String, dynamic> json) => InvoiceLine(
      lineNo: json['line_no'] as int,
      itemId: json['item_id'] as String?,
      itemCode: json['item_code'] as String,
      itemName: json['item_name'] as String,
      hsnCode: json['hsn_code'] as String?,
      sacCode: json['sac_code'] as String?,
      quantity: (json['quantity'] as num).toDouble(),
      unit: json['unit'] as String,
      unitPrice: (json['unit_price'] as num).toDouble(),
      discountAmount: (json['discount_amount'] as num).toDouble(),
      taxableValue: (json['taxable_value'] as num).toDouble(),
      gstRate: (json['gst_rate'] as num).toDouble(),
      cgstAmount: (json['cgst_amount'] as num).toDouble(),
      sgstAmount: (json['sgst_amount'] as num).toDouble(),
      igstAmount: (json['igst_amount'] as num).toDouble(),
      cessAmount: (json['cess_amount'] as num).toDouble(),
      totalAmount: (json['total_amount'] as num).toDouble(),
    );