// This file is auto-generated by json_serializable. Do not edit manually.

part of 'party.dart';

Map<String, dynamic> _$PartyToJson(Party instance) => <String, dynamic>{
      'party_id': instance.partyId,
      'party_name': instance.partyName,
      'party_type': instance.partyType,
      'gstin': instance.gstin,
      'pan': instance.pan,
      'state_code': instance.stateCode,
      'party_category': instance.partyCategory,
      'credit_limit': instance.creditLimit,
      'credit_days': instance.creditDays,
      'opening_balance': instance.openingBalance,
      'tds_applicable': instance.tdsApplicable,
      'addresses': instance.addresses,
      'contacts': instance.contacts,
      'bank_accounts': instance.bankAccounts,
    };

Party _$PartyFromJson(Map<String, dynamic> json) => Party(
      partyId: json['party_id'] as String,
      partyName: json['party_name'] as String,
      partyType: json['party_type'] as String,
      gstin: json['gstin'] as String?,
      pan: json['pan'] as String?,
      stateCode: json['state_code'] as String?,
      partyCategory: json['party_category'] as String?,
      creditLimit: (json['credit_limit'] as num).toDouble(),
      creditDays: json['credit_days'] as int,
      openingBalance: (json['opening_balance'] as num).toDouble(),
      tdsApplicable: json['tds_applicable'] as bool,
      addresses: (json['addresses'] as List<dynamic>?)?.cast<Map<String, dynamic>>() ?? [],
      contacts: (json['contacts'] as List<dynamic>?)?.cast<Map<String, dynamic>>() ?? [],
      bankAccounts: (json['bank_accounts'] as List<dynamic>?)?.cast<Map<String, dynamic>>() ?? [],
    );