// This file is auto-generated by json_serializable. Do not edit manually.

part of 'payment.dart';

Map<String, dynamic> _$PaymentToJson(Payment instance) => <String, dynamic>{
      'payment_id': instance.paymentId,
      'payment_type': instance.paymentType,
      'payment_mode': instance.paymentMode,
      'payment_date': instance.paymentDate.toIso8601String(),
      'party_id': instance.partyId,
      'amount': instance.amount,
      'tds_amount': instance.tdsAmount,
      'net_amount': instance.netAmount,
      'reference_no': instance.referenceNo,
      'narration': instance.narration,
      'status': instance.status,
      'allocations': instance.allocations,
    };

Payment _$PaymentFromJson(Map<String, dynamic> json) => Payment(
      paymentId: json['payment_id'] as String,
      paymentType: json['payment_type'] as String,
      paymentMode: json['payment_mode'] as String,
      paymentDate: DateTime.parse(json['payment_date'] as String),
      partyId: json['party_id'] as String,
      amount: (json['amount'] as num).toDouble(),
      tdsAmount: (json['tds_amount'] as num).toDouble(),
      netAmount: (json['net_amount'] as num).toDouble(),
      referenceNo: json['reference_no'] as String,
      narration: json['narration'] as String,
      status: json['status'] as String,
      allocations: (json['allocations'] as List<dynamic>?)?.cast<Map<String, dynamic>>() ?? [],
    );