// This file is auto-generated by json_serializable. Do not edit manually.

part of 'user.dart';

Map<String, dynamic> _$UserToJson(User instance) => <String, dynamic>{
      'user_id': instance.userId,
      'email': instance.email,
      'full_name': instance.fullName,
      'roles': instance.roles,
      'permissions': instance.permissions,
    };

User _$UserFromJson(Map<String, dynamic> json) => User(
      userId: json['user_id'] as String,
      email: json['email'] as String,
      fullName: json['full_name'] as String,
      roles: (json['roles'] as List<dynamic>?)?.cast<String>() ?? [],
      permissions: (json['permissions'] as List<dynamic>?)?.cast<String>() ?? [],
    );